// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	Name      string `json:"name"`
	CompanyID int    `json:"companyId"`
}
