// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/user.proto

package _go

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CompanyId            uint64   `protobuf:"varint,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_758175df987a0569, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCompanyId() uint64 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

type RegisterUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CompanyId            uint64   `protobuf:"varint,4,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_758175df987a0569, []int{1}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterUserRequest) GetCompanyId() uint64 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

type RegisterUserResponse struct {
	UserUuid             string   `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_758175df987a0569, []int{2}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

type VerifyUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserRequest) Reset()         { *m = VerifyUserRequest{} }
func (m *VerifyUserRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyUserRequest) ProtoMessage()    {}
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_758175df987a0569, []int{3}
}

func (m *VerifyUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserRequest.Unmarshal(m, b)
}
func (m *VerifyUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserRequest.Marshal(b, m, deterministic)
}
func (m *VerifyUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserRequest.Merge(m, src)
}
func (m *VerifyUserRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyUserRequest.Size(m)
}
func (m *VerifyUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserRequest proto.InternalMessageInfo

func (m *VerifyUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyUserResponse struct {
	NewToken             string   `protobuf:"bytes,1,opt,name=newToken,proto3" json:"newToken,omitempty"`
	OldToken             string   `protobuf:"bytes,2,opt,name=oldToken,proto3" json:"oldToken,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserResponse) Reset()         { *m = VerifyUserResponse{} }
func (m *VerifyUserResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyUserResponse) ProtoMessage()    {}
func (*VerifyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_758175df987a0569, []int{4}
}

func (m *VerifyUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserResponse.Unmarshal(m, b)
}
func (m *VerifyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserResponse.Marshal(b, m, deterministic)
}
func (m *VerifyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserResponse.Merge(m, src)
}
func (m *VerifyUserResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyUserResponse.Size(m)
}
func (m *VerifyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserResponse proto.InternalMessageInfo

func (m *VerifyUserResponse) GetNewToken() string {
	if m != nil {
		return m.NewToken
	}
	return ""
}

func (m *VerifyUserResponse) GetOldToken() string {
	if m != nil {
		return m.OldToken
	}
	return ""
}

func (m *VerifyUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SendRecoverEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRecoverEmailRequest) Reset()         { *m = SendRecoverEmailRequest{} }
func (m *SendRecoverEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendRecoverEmailRequest) ProtoMessage()    {}
func (*SendRecoverEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_758175df987a0569, []int{5}
}

func (m *SendRecoverEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRecoverEmailRequest.Unmarshal(m, b)
}
func (m *SendRecoverEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRecoverEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendRecoverEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRecoverEmailRequest.Merge(m, src)
}
func (m *SendRecoverEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendRecoverEmailRequest.Size(m)
}
func (m *SendRecoverEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRecoverEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRecoverEmailRequest proto.InternalMessageInfo

func (m *SendRecoverEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendRecoverEmailRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SendRecoverEmailResponse struct {
	AuthKey              string   `protobuf:"bytes,1,opt,name=authKey,proto3" json:"authKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRecoverEmailResponse) Reset()         { *m = SendRecoverEmailResponse{} }
func (m *SendRecoverEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendRecoverEmailResponse) ProtoMessage()    {}
func (*SendRecoverEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_758175df987a0569, []int{6}
}

func (m *SendRecoverEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRecoverEmailResponse.Unmarshal(m, b)
}
func (m *SendRecoverEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRecoverEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendRecoverEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRecoverEmailResponse.Merge(m, src)
}
func (m *SendRecoverEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendRecoverEmailResponse.Size(m)
}
func (m *SendRecoverEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRecoverEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendRecoverEmailResponse proto.InternalMessageInfo

func (m *SendRecoverEmailResponse) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

type RecoverPasswordRequest struct {
	RecoverToken         string   `protobuf:"bytes,1,opt,name=recoverToken,proto3" json:"recoverToken,omitempty"`
	AuthKey              string   `protobuf:"bytes,2,opt,name=authKey,proto3" json:"authKey,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverPasswordRequest) Reset()         { *m = RecoverPasswordRequest{} }
func (m *RecoverPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverPasswordRequest) ProtoMessage()    {}
func (*RecoverPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_758175df987a0569, []int{7}
}

func (m *RecoverPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverPasswordRequest.Unmarshal(m, b)
}
func (m *RecoverPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverPasswordRequest.Marshal(b, m, deterministic)
}
func (m *RecoverPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverPasswordRequest.Merge(m, src)
}
func (m *RecoverPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverPasswordRequest.Size(m)
}
func (m *RecoverPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverPasswordRequest proto.InternalMessageInfo

func (m *RecoverPasswordRequest) GetRecoverToken() string {
	if m != nil {
		return m.RecoverToken
	}
	return ""
}

func (m *RecoverPasswordRequest) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

func (m *RecoverPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "account.User")
	proto.RegisterType((*RegisterUserRequest)(nil), "account.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "account.RegisterUserResponse")
	proto.RegisterType((*VerifyUserRequest)(nil), "account.VerifyUserRequest")
	proto.RegisterType((*VerifyUserResponse)(nil), "account.VerifyUserResponse")
	proto.RegisterType((*SendRecoverEmailRequest)(nil), "account.SendRecoverEmailRequest")
	proto.RegisterType((*SendRecoverEmailResponse)(nil), "account.SendRecoverEmailResponse")
	proto.RegisterType((*RecoverPasswordRequest)(nil), "account.RecoverPasswordRequest")
}

func init() {
	proto.RegisterFile("proto/account/user.proto", fileDescriptor_758175df987a0569)
}

var fileDescriptor_758175df987a0569 = []byte{
	// 639 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x7e, 0xed, 0xa6, 0x1f, 0x99, 0xb6, 0x2f, 0xed, 0x52, 0x8a, 0xe5, 0x52, 0x25, 0xb5, 0x40,
	0x2a, 0x94, 0xd8, 0x6a, 0xcb, 0xe7, 0x0d, 0x45, 0x2a, 0x12, 0xf4, 0x52, 0xa5, 0x2d, 0x54, 0xf4,
	0x4b, 0x8e, 0x77, 0x9b, 0x2e, 0x4d, 0xbc, 0x61, 0x6d, 0xd7, 0x44, 0x08, 0x6e, 0x1c, 0x38, 0xf3,
	0x9f, 0xf8, 0x13, 0x1c, 0x22, 0xe5, 0x8f, 0x80, 0x76, 0xbd, 0x36, 0x76, 0x9b, 0x22, 0x2e, 0x48,
	0xdc, 0xe6, 0x99, 0x19, 0xcf, 0xce, 0xf3, 0xcc, 0x78, 0xc0, 0xe8, 0x72, 0x16, 0x32, 0xc7, 0xf5,
	0x3c, 0x16, 0xf9, 0xa1, 0x13, 0x05, 0x84, 0xdb, 0xd2, 0x85, 0xc6, 0x95, 0xcf, 0x7c, 0xd4, 0xa2,
	0xe1, 0x69, 0xd4, 0xb4, 0x3d, 0xd6, 0x71, 0x3a, 0x31, 0x0d, 0xcf, 0x58, 0xec, 0xb4, 0x58, 0x4d,
	0x66, 0xd5, 0xce, 0xdd, 0x36, 0xc5, 0x6e, 0xc8, 0x78, 0xe0, 0x64, 0x66, 0x52, 0xc0, 0x5c, 0x68,
	0x31, 0xd6, 0x6a, 0x13, 0x47, 0xa2, 0x66, 0x74, 0xe2, 0x90, 0x4e, 0x37, 0xec, 0x25, 0x41, 0x2b,
	0x80, 0xd2, 0x6e, 0x40, 0x38, 0xfa, 0x1f, 0x74, 0x8a, 0x0d, 0xad, 0xaa, 0x2d, 0x97, 0x1a, 0x3a,
	0xc5, 0x08, 0x41, 0x29, 0x8a, 0x28, 0x36, 0xf4, 0xaa, 0xb6, 0x5c, 0x6e, 0x48, 0x1b, 0xcd, 0xc1,
	0x28, 0xe9, 0xb8, 0xb4, 0x6d, 0x8c, 0x48, 0x67, 0x02, 0x44, 0xa6, 0xef, 0x76, 0x88, 0x51, 0x4a,
	0x32, 0x85, 0x8d, 0x16, 0x01, 0x3c, 0xd6, 0xe9, 0xba, 0x7e, 0xef, 0x98, 0x62, 0x63, 0x54, 0x56,
	0x2d, 0x2b, 0xcf, 0x0b, 0x6c, 0x7d, 0xd7, 0xe0, 0x7a, 0x83, 0xb4, 0x68, 0x10, 0x12, 0x2e, 0x5e,
	0x6f, 0x90, 0x77, 0x11, 0x09, 0x42, 0xb4, 0x99, 0x3e, 0x20, 0xfa, 0x28, 0xd7, 0x1f, 0x0e, 0xfa,
	0x95, 0x55, 0xa8, 0x1d, 0x1d, 0xc4, 0x2b, 0xcb, 0xfb, 0xb5, 0x15, 0xfb, 0xf0, 0x20, 0x5e, 0xb9,
	0x7b, 0xef, 0x59, 0x02, 0x15, 0x3a, 0xb0, 0x0b, 0xf0, 0xf6, 0x9e, 0x96, 0xf6, 0xb5, 0x0a, 0x13,
	0x5d, 0x37, 0x08, 0x62, 0xc6, 0x15, 0x8b, 0xfa, 0x8d, 0x41, 0xbf, 0x32, 0x0b, 0xd3, 0x47, 0xfb,
	0xd5, 0xda, 0xa7, 0xc3, 0x0f, 0x4f, 0xee, 0xaf, 0xaf, 0x7d, 0x14, 0xf9, 0x59, 0x1a, 0x5a, 0x54,
	0x54, 0x24, 0xbf, 0x7a, 0x79, 0xd0, 0xaf, 0x8c, 0xee, 0x69, 0xef, 0x7f, 0x68, 0x8a, 0xd5, 0x9d,
	0x02, 0x2b, 0xc1, 0xb7, 0x54, 0x1f, 0x1b, 0xf4, 0x2b, 0xfa, 0xcc, 0x7f, 0x79, 0x76, 0xeb, 0x30,
	0x57, 0x24, 0x17, 0x74, 0x99, 0x1f, 0x10, 0xb4, 0x00, 0x65, 0x31, 0xd6, 0x63, 0xa9, 0xab, 0x64,
	0xd8, 0x98, 0x10, 0x8e, 0xdd, 0x88, 0x62, 0xeb, 0xab, 0x06, 0xb3, 0xaf, 0x08, 0xa7, 0x27, 0xbd,
	0x7f, 0x48, 0x10, 0x8b, 0x01, 0xca, 0x37, 0xa5, 0x88, 0x98, 0x30, 0xe1, 0x93, 0x78, 0x87, 0x9d,
	0x11, 0x3f, 0xe5, 0x91, 0x62, 0x11, 0x63, 0x6d, 0x9c, 0xc4, 0x92, 0xdd, 0xc9, 0x30, 0x5a, 0x82,
	0x92, 0xe0, 0x2b, 0xe5, 0x9d, 0x5c, 0x9b, 0xb6, 0xd5, 0x62, 0xdb, 0xb2, 0xb8, 0x0c, 0x59, 0x9f,
	0x35, 0xb8, 0xb9, 0x4d, 0x7c, 0xdc, 0x20, 0x1e, 0x3b, 0x27, 0x7c, 0x43, 0x34, 0xfe, 0x57, 0xc4,
	0x48, 0x47, 0xad, 0x0f, 0x1d, 0xb5, 0xf5, 0x00, 0x8c, 0xcb, 0x6d, 0x28, 0xfa, 0x06, 0x8c, 0xbb,
	0x51, 0x78, 0xba, 0x49, 0x7a, 0x8a, 0x7d, 0x0a, 0xad, 0x2f, 0x1a, 0xcc, 0xab, 0x4f, 0xb6, 0x94,
	0x84, 0x69, 0xf3, 0x16, 0x4c, 0xf1, 0x24, 0x92, 0xd7, 0xad, 0xe0, 0xcb, 0x17, 0xd6, 0x0b, 0x85,
	0x0b, 0xa3, 0x1b, 0xf9, 0xa3, 0xd1, 0xad, 0x7d, 0xd3, 0x61, 0x52, 0x08, 0xbb, 0x4d, 0xf8, 0x39,
	0xf5, 0x08, 0xda, 0x84, 0xa9, 0xfc, 0x56, 0xa2, 0x5b, 0x99, 0xfc, 0x43, 0xfe, 0x44, 0x73, 0xf1,
	0x8a, 0xa8, 0x92, 0x60, 0x03, 0xe0, 0xd7, 0x5e, 0x20, 0x33, 0x4b, 0xbe, 0xb4, 0xc1, 0xe6, 0xc2,
	0xd0, 0x98, 0x2a, 0xf3, 0x1a, 0x66, 0x2e, 0xaa, 0x8c, 0xaa, 0xd9, 0x07, 0x57, 0xec, 0x81, 0xb9,
	0xf4, 0x9b, 0x0c, 0x55, 0xf8, 0x25, 0x5c, 0xbb, 0x30, 0x07, 0x54, 0xc9, 0x31, 0x1a, 0x36, 0x21,
	0x73, 0xde, 0x4e, 0xee, 0xa4, 0x9d, 0xde, 0x49, 0x7b, 0x43, 0xdc, 0xc9, 0xfa, 0xd3, 0x37, 0x8f,
	0x73, 0x87, 0x77, 0x87, 0x13, 0x1f, 0x3f, 0xa7, 0x3e, 0xde, 0xe2, 0xec, 0x2d, 0xf1, 0x42, 0x27,
	0x3c, 0x39, 0x6e, 0xba, 0xde, 0x19, 0xf1, 0xb1, 0x53, 0x3c, 0xe1, 0x2d, 0xd6, 0x1c, 0x93, 0x9e,
	0xf5, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x74, 0xb9, 0xc4, 0x12, 0xdd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error)
	SendRecoverEmail(ctx context.Context, in *SendRecoverEmailRequest, opts ...grpc.CallOption) (*SendRecoverEmailResponse, error)
	RecoverPassword(ctx context.Context, in *RecoverPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/account.UserService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error) {
	out := new(VerifyUserResponse)
	err := c.cc.Invoke(ctx, "/account.UserService/VerifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendRecoverEmail(ctx context.Context, in *SendRecoverEmailRequest, opts ...grpc.CallOption) (*SendRecoverEmailResponse, error) {
	out := new(SendRecoverEmailResponse)
	err := c.cc.Invoke(ctx, "/account.UserService/SendRecoverEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RecoverPassword(ctx context.Context, in *RecoverPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.UserService/RecoverPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	VerifyUser(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error)
	SendRecoverEmail(context.Context, *SendRecoverEmailRequest) (*SendRecoverEmailResponse, error)
	RecoverPassword(context.Context, *RecoverPasswordRequest) (*empty.Empty, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedUserServiceServer) VerifyUser(ctx context.Context, req *VerifyUserRequest) (*VerifyUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUser not implemented")
}
func (*UnimplementedUserServiceServer) SendRecoverEmail(ctx context.Context, req *SendRecoverEmailRequest) (*SendRecoverEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRecoverEmail not implemented")
}
func (*UnimplementedUserServiceServer) RecoverPassword(ctx context.Context, req *RecoverPasswordRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverPassword not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.UserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.UserService/VerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyUser(ctx, req.(*VerifyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendRecoverEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRecoverEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendRecoverEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.UserService/SendRecoverEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendRecoverEmail(ctx, req.(*SendRecoverEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RecoverPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RecoverPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.UserService/RecoverPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RecoverPassword(ctx, req.(*RecoverPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
		{
			MethodName: "VerifyUser",
			Handler:    _UserService_VerifyUser_Handler,
		},
		{
			MethodName: "SendRecoverEmail",
			Handler:    _UserService_SendRecoverEmail_Handler,
		},
		{
			MethodName: "RecoverPassword",
			Handler:    _UserService_RecoverPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/account/user.proto",
}
