steps:
  # build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/trend-find-algorithm:$SHORT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/trend-find-algorithm:latest",
        ".",
      ]
    dir: "app"
  # upload image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/trend-find-algorithm:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/trend-find-algorithm:latest"]
  # deploy cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'trend-find-algorithm',
        '--image',
        'gcr.io/$PROJECT_ID/trend-find-algorithm',
        '--region',
        'asia-northeast1',
        '--platform',
        'managed',
      ]
images:
  - gcr.io/$PROJECT_ID/trend-find-algorithm
