version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: 2929ml
    ports:
      - "8080:8080"
    environment:
      - "PORT=8080"
      - "ENV=LOCAL"
    volumes:
      - ./app:/app
  mysql:
    build:
      context: ./
      dockerfile: mysql/Dockerfile
    container_name: 2929mysql_algorithm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trend
      MYSQL_USER: 2929
      MYSQL_PASSWORD: 2929
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
