steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/trend-find-frontend:$SHORT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/trend-find-frontend:latest",
        "--build-arg",
        "APIURL_ENV=$_APIURL_ENV",
        "--build-arg",
        "COOKIE_DOMAIN=$_COOKIE_DOMAIN",
        ".",
      ]
  # upload image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/trend-find-frontend:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/trend-find-frontend:latest"]
  # upload gke
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment",
        "frontend",
        "frontend=gcr.io/$PROJECT_ID/trend-find-frontend:$SHORT_SHA",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER"
