# フロントエンドのdocker環境
up.front:
	docker-compose up frontend

# フロントエンドのローカル環境 (ローカルのバックエンドに接続)
run.local.front:
	cd ./frontend && npm run dev

# フロントエンドのローカル環境 (スタブへ接続)
run.local.stub:
	cd ./frontend && npm run stub

# ESLintの実行
run.eslint:
	cd ./frontend && npm run lint

# GraphQLスタブ
run.stub:
	cd ./graphql-stub && npm run start