// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/trend/trend.proto

package _go

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Suggest) Validate() error {
	for _, item := range this.ChildSuggests {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ChildSuggests", err)
			}
		}
	}
	return nil
}
func (this *ChildSuggest) Validate() error {
	if this.Growth != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Growth); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Growth", err)
		}
	}
	if this.Graphs != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Graphs); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Graphs", err)
		}
	}
	return nil
}
func (this *Growth) Validate() error {
	return nil
}
func (this *Graphs) Validate() error {
	for _, item := range this.Short {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Short", err)
			}
		}
	}
	for _, item := range this.Medium {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Medium", err)
			}
		}
	}
	for _, item := range this.Long {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Long", err)
			}
		}
	}
	return nil
}
func (this *Graph) Validate() error {
	return nil
}
func (this *History) Validate() error {
	return nil
}
func (this *TrendSearchRequest) Validate() error {
	return nil
}
func (this *TrendSearchResponse) Validate() error {
	return nil
}
func (this *TrendSuggestRequest) Validate() error {
	return nil
}
func (this *TrendSuggestResponse) Validate() error {
	for _, item := range this.Suggest {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Suggest", err)
			}
		}
	}
	return nil
}
func (this *TrendHistoryRequest) Validate() error {
	return nil
}
func (this *TrendHistoryResponse) Validate() error {
	for _, item := range this.Histories {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Histories", err)
			}
		}
	}
	return nil
}
