// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/trend/trend.proto

package _go

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Arrow int32

const (
	Arrow_UP   Arrow = 0
	Arrow_FLAT Arrow = 1
	Arrow_DOWN Arrow = 2
)

var Arrow_name = map[int32]string{
	0: "UP",
	1: "FLAT",
	2: "DOWN",
}

var Arrow_value = map[string]int32{
	"UP":   0,
	"FLAT": 1,
	"DOWN": 2,
}

func (x Arrow) String() string {
	return proto.EnumName(Arrow_name, int32(x))
}

func (Arrow) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{0}
}

type Progress int32

const (
	Progress_IN_PROGRESS Progress = 0
	Progress_COMPLETED   Progress = 1
)

var Progress_name = map[int32]string{
	0: "IN_PROGRESS",
	1: "COMPLETED",
}

var Progress_value = map[string]int32{
	"IN_PROGRESS": 0,
	"COMPLETED":   1,
}

func (x Progress) String() string {
	return proto.EnumName(Progress_name, int32(x))
}

func (Progress) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{1}
}

type Suggest struct {
	SuggestWord          string          `protobuf:"bytes,1,opt,name=suggestWord,proto3" json:"suggestWord,omitempty"`
	ChildSuggests        []*ChildSuggest `protobuf:"bytes,2,rep,name=childSuggests,proto3" json:"childSuggests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Suggest) Reset()         { *m = Suggest{} }
func (m *Suggest) String() string { return proto.CompactTextString(m) }
func (*Suggest) ProtoMessage()    {}
func (*Suggest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{0}
}

func (m *Suggest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suggest.Unmarshal(m, b)
}
func (m *Suggest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suggest.Marshal(b, m, deterministic)
}
func (m *Suggest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suggest.Merge(m, src)
}
func (m *Suggest) XXX_Size() int {
	return xxx_messageInfo_Suggest.Size(m)
}
func (m *Suggest) XXX_DiscardUnknown() {
	xxx_messageInfo_Suggest.DiscardUnknown(m)
}

var xxx_messageInfo_Suggest proto.InternalMessageInfo

func (m *Suggest) GetSuggestWord() string {
	if m != nil {
		return m.SuggestWord
	}
	return ""
}

func (m *Suggest) GetChildSuggests() []*ChildSuggest {
	if m != nil {
		return m.ChildSuggests
	}
	return nil
}

type ChildSuggest struct {
	ChildSuggestWord     string   `protobuf:"bytes,1,opt,name=childSuggestWord,proto3" json:"childSuggestWord,omitempty"`
	Growth               *Growth  `protobuf:"bytes,2,opt,name=growth,proto3" json:"growth,omitempty"`
	Graphs               *Graphs  `protobuf:"bytes,3,opt,name=graphs,proto3" json:"graphs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChildSuggest) Reset()         { *m = ChildSuggest{} }
func (m *ChildSuggest) String() string { return proto.CompactTextString(m) }
func (*ChildSuggest) ProtoMessage()    {}
func (*ChildSuggest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{1}
}

func (m *ChildSuggest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChildSuggest.Unmarshal(m, b)
}
func (m *ChildSuggest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChildSuggest.Marshal(b, m, deterministic)
}
func (m *ChildSuggest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChildSuggest.Merge(m, src)
}
func (m *ChildSuggest) XXX_Size() int {
	return xxx_messageInfo_ChildSuggest.Size(m)
}
func (m *ChildSuggest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChildSuggest.DiscardUnknown(m)
}

var xxx_messageInfo_ChildSuggest proto.InternalMessageInfo

func (m *ChildSuggest) GetChildSuggestWord() string {
	if m != nil {
		return m.ChildSuggestWord
	}
	return ""
}

func (m *ChildSuggest) GetGrowth() *Growth {
	if m != nil {
		return m.Growth
	}
	return nil
}

func (m *ChildSuggest) GetGraphs() *Graphs {
	if m != nil {
		return m.Graphs
	}
	return nil
}

type Growth struct {
	Short                Arrow    `protobuf:"varint,1,opt,name=short,proto3,enum=trend.Arrow" json:"short,omitempty"`
	Medium               Arrow    `protobuf:"varint,2,opt,name=medium,proto3,enum=trend.Arrow" json:"medium,omitempty"`
	Long                 Arrow    `protobuf:"varint,3,opt,name=long,proto3,enum=trend.Arrow" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Growth) Reset()         { *m = Growth{} }
func (m *Growth) String() string { return proto.CompactTextString(m) }
func (*Growth) ProtoMessage()    {}
func (*Growth) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{2}
}

func (m *Growth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Growth.Unmarshal(m, b)
}
func (m *Growth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Growth.Marshal(b, m, deterministic)
}
func (m *Growth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Growth.Merge(m, src)
}
func (m *Growth) XXX_Size() int {
	return xxx_messageInfo_Growth.Size(m)
}
func (m *Growth) XXX_DiscardUnknown() {
	xxx_messageInfo_Growth.DiscardUnknown(m)
}

var xxx_messageInfo_Growth proto.InternalMessageInfo

func (m *Growth) GetShort() Arrow {
	if m != nil {
		return m.Short
	}
	return Arrow_UP
}

func (m *Growth) GetMedium() Arrow {
	if m != nil {
		return m.Medium
	}
	return Arrow_UP
}

func (m *Growth) GetLong() Arrow {
	if m != nil {
		return m.Long
	}
	return Arrow_UP
}

type Graphs struct {
	Short                []*Graph `protobuf:"bytes,1,rep,name=short,proto3" json:"short,omitempty"`
	Medium               []*Graph `protobuf:"bytes,2,rep,name=medium,proto3" json:"medium,omitempty"`
	Long                 []*Graph `protobuf:"bytes,3,rep,name=long,proto3" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Graphs) Reset()         { *m = Graphs{} }
func (m *Graphs) String() string { return proto.CompactTextString(m) }
func (*Graphs) ProtoMessage()    {}
func (*Graphs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{3}
}

func (m *Graphs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Graphs.Unmarshal(m, b)
}
func (m *Graphs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Graphs.Marshal(b, m, deterministic)
}
func (m *Graphs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graphs.Merge(m, src)
}
func (m *Graphs) XXX_Size() int {
	return xxx_messageInfo_Graphs.Size(m)
}
func (m *Graphs) XXX_DiscardUnknown() {
	xxx_messageInfo_Graphs.DiscardUnknown(m)
}

var xxx_messageInfo_Graphs proto.InternalMessageInfo

func (m *Graphs) GetShort() []*Graph {
	if m != nil {
		return m.Short
	}
	return nil
}

func (m *Graphs) GetMedium() []*Graph {
	if m != nil {
		return m.Medium
	}
	return nil
}

func (m *Graphs) GetLong() []*Graph {
	if m != nil {
		return m.Long
	}
	return nil
}

type Graph struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Graph) Reset()         { *m = Graph{} }
func (m *Graph) String() string { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()    {}
func (*Graph) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{4}
}

func (m *Graph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Graph.Unmarshal(m, b)
}
func (m *Graph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Graph.Marshal(b, m, deterministic)
}
func (m *Graph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph.Merge(m, src)
}
func (m *Graph) XXX_Size() int {
	return xxx_messageInfo_Graph.Size(m)
}
func (m *Graph) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph.DiscardUnknown(m)
}

var xxx_messageInfo_Graph proto.InternalMessageInfo

func (m *Graph) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Graph) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type History struct {
	SearchId             uint64   `protobuf:"varint,1,opt,name=searchId,proto3" json:"searchId,omitempty"`
	SearchWord           string   `protobuf:"bytes,2,opt,name=searchWord,proto3" json:"searchWord,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Status               Progress `protobuf:"varint,4,opt,name=status,proto3,enum=trend.Progress" json:"status,omitempty"`
	IsRead               bool     `protobuf:"varint,5,opt,name=isRead,proto3" json:"isRead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{5}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetSearchId() uint64 {
	if m != nil {
		return m.SearchId
	}
	return 0
}

func (m *History) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *History) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *History) GetStatus() Progress {
	if m != nil {
		return m.Status
	}
	return Progress_IN_PROGRESS
}

func (m *History) GetIsRead() bool {
	if m != nil {
		return m.IsRead
	}
	return false
}

type TrendSearchRequest struct {
	SearchWord           string   `protobuf:"bytes,1,opt,name=searchWord,proto3" json:"searchWord,omitempty"`
	UserUuid             string   `protobuf:"bytes,2,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrendSearchRequest) Reset()         { *m = TrendSearchRequest{} }
func (m *TrendSearchRequest) String() string { return proto.CompactTextString(m) }
func (*TrendSearchRequest) ProtoMessage()    {}
func (*TrendSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{6}
}

func (m *TrendSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrendSearchRequest.Unmarshal(m, b)
}
func (m *TrendSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrendSearchRequest.Marshal(b, m, deterministic)
}
func (m *TrendSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrendSearchRequest.Merge(m, src)
}
func (m *TrendSearchRequest) XXX_Size() int {
	return xxx_messageInfo_TrendSearchRequest.Size(m)
}
func (m *TrendSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrendSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrendSearchRequest proto.InternalMessageInfo

func (m *TrendSearchRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *TrendSearchRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

type TrendSearchResponse struct {
	SearchId             uint64   `protobuf:"varint,1,opt,name=searchId,proto3" json:"searchId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrendSearchResponse) Reset()         { *m = TrendSearchResponse{} }
func (m *TrendSearchResponse) String() string { return proto.CompactTextString(m) }
func (*TrendSearchResponse) ProtoMessage()    {}
func (*TrendSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{7}
}

func (m *TrendSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrendSearchResponse.Unmarshal(m, b)
}
func (m *TrendSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrendSearchResponse.Marshal(b, m, deterministic)
}
func (m *TrendSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrendSearchResponse.Merge(m, src)
}
func (m *TrendSearchResponse) XXX_Size() int {
	return xxx_messageInfo_TrendSearchResponse.Size(m)
}
func (m *TrendSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrendSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrendSearchResponse proto.InternalMessageInfo

func (m *TrendSearchResponse) GetSearchId() uint64 {
	if m != nil {
		return m.SearchId
	}
	return 0
}

type TrendSuggestRequest struct {
	SearchId             uint64   `protobuf:"varint,1,opt,name=searchId,proto3" json:"searchId,omitempty"`
	UserUuid             string   `protobuf:"bytes,2,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrendSuggestRequest) Reset()         { *m = TrendSuggestRequest{} }
func (m *TrendSuggestRequest) String() string { return proto.CompactTextString(m) }
func (*TrendSuggestRequest) ProtoMessage()    {}
func (*TrendSuggestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{8}
}

func (m *TrendSuggestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrendSuggestRequest.Unmarshal(m, b)
}
func (m *TrendSuggestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrendSuggestRequest.Marshal(b, m, deterministic)
}
func (m *TrendSuggestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrendSuggestRequest.Merge(m, src)
}
func (m *TrendSuggestRequest) XXX_Size() int {
	return xxx_messageInfo_TrendSuggestRequest.Size(m)
}
func (m *TrendSuggestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrendSuggestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrendSuggestRequest proto.InternalMessageInfo

func (m *TrendSuggestRequest) GetSearchId() uint64 {
	if m != nil {
		return m.SearchId
	}
	return 0
}

func (m *TrendSuggestRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

type TrendSuggestResponse struct {
	Suggest              []*Suggest `protobuf:"bytes,1,rep,name=suggest,proto3" json:"suggest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TrendSuggestResponse) Reset()         { *m = TrendSuggestResponse{} }
func (m *TrendSuggestResponse) String() string { return proto.CompactTextString(m) }
func (*TrendSuggestResponse) ProtoMessage()    {}
func (*TrendSuggestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{9}
}

func (m *TrendSuggestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrendSuggestResponse.Unmarshal(m, b)
}
func (m *TrendSuggestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrendSuggestResponse.Marshal(b, m, deterministic)
}
func (m *TrendSuggestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrendSuggestResponse.Merge(m, src)
}
func (m *TrendSuggestResponse) XXX_Size() int {
	return xxx_messageInfo_TrendSuggestResponse.Size(m)
}
func (m *TrendSuggestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrendSuggestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrendSuggestResponse proto.InternalMessageInfo

func (m *TrendSuggestResponse) GetSuggest() []*Suggest {
	if m != nil {
		return m.Suggest
	}
	return nil
}

type TrendHistoryRequest struct {
	UserUuid             string   `protobuf:"bytes,1,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrendHistoryRequest) Reset()         { *m = TrendHistoryRequest{} }
func (m *TrendHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*TrendHistoryRequest) ProtoMessage()    {}
func (*TrendHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{10}
}

func (m *TrendHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrendHistoryRequest.Unmarshal(m, b)
}
func (m *TrendHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrendHistoryRequest.Marshal(b, m, deterministic)
}
func (m *TrendHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrendHistoryRequest.Merge(m, src)
}
func (m *TrendHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_TrendHistoryRequest.Size(m)
}
func (m *TrendHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrendHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrendHistoryRequest proto.InternalMessageInfo

func (m *TrendHistoryRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

type TrendHistoryResponse struct {
	Histories            []*History `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TrendHistoryResponse) Reset()         { *m = TrendHistoryResponse{} }
func (m *TrendHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*TrendHistoryResponse) ProtoMessage()    {}
func (*TrendHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f85e6b6f281f975, []int{11}
}

func (m *TrendHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrendHistoryResponse.Unmarshal(m, b)
}
func (m *TrendHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrendHistoryResponse.Marshal(b, m, deterministic)
}
func (m *TrendHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrendHistoryResponse.Merge(m, src)
}
func (m *TrendHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_TrendHistoryResponse.Size(m)
}
func (m *TrendHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrendHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrendHistoryResponse proto.InternalMessageInfo

func (m *TrendHistoryResponse) GetHistories() []*History {
	if m != nil {
		return m.Histories
	}
	return nil
}

func init() {
	proto.RegisterEnum("trend.Arrow", Arrow_name, Arrow_value)
	proto.RegisterEnum("trend.Progress", Progress_name, Progress_value)
	proto.RegisterType((*Suggest)(nil), "trend.Suggest")
	proto.RegisterType((*ChildSuggest)(nil), "trend.ChildSuggest")
	proto.RegisterType((*Growth)(nil), "trend.Growth")
	proto.RegisterType((*Graphs)(nil), "trend.Graphs")
	proto.RegisterType((*Graph)(nil), "trend.Graph")
	proto.RegisterType((*History)(nil), "trend.History")
	proto.RegisterType((*TrendSearchRequest)(nil), "trend.TrendSearchRequest")
	proto.RegisterType((*TrendSearchResponse)(nil), "trend.TrendSearchResponse")
	proto.RegisterType((*TrendSuggestRequest)(nil), "trend.TrendSuggestRequest")
	proto.RegisterType((*TrendSuggestResponse)(nil), "trend.TrendSuggestResponse")
	proto.RegisterType((*TrendHistoryRequest)(nil), "trend.TrendHistoryRequest")
	proto.RegisterType((*TrendHistoryResponse)(nil), "trend.TrendHistoryResponse")
}

func init() {
	proto.RegisterFile("proto/trend/trend.proto", fileDescriptor_3f85e6b6f281f975)
}

var fileDescriptor_3f85e6b6f281f975 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdd, 0x4e, 0xdc, 0x3c,
	0x10, 0x25, 0xfb, 0x13, 0x96, 0xd9, 0x05, 0x22, 0x83, 0xbe, 0x2f, 0xdd, 0x4a, 0x55, 0x94, 0xb6,
	0xea, 0x6a, 0x55, 0x81, 0xd8, 0xaa, 0xaa, 0x7a, 0x57, 0xca, 0x02, 0x45, 0xe2, 0x27, 0xf2, 0x82,
	0x90, 0x7a, 0x83, 0x42, 0x62, 0x92, 0xb4, 0xb0, 0xa6, 0xb6, 0x03, 0xea, 0x1b, 0xf4, 0x19, 0xfa,
	0x80, 0x7d, 0x8e, 0x2a, 0x8e, 0x93, 0x3a, 0x09, 0xda, 0x9b, 0xc8, 0x33, 0xe7, 0x78, 0xce, 0xf1,
	0x8c, 0x63, 0xf8, 0xff, 0x9e, 0x51, 0x41, 0xb7, 0x05, 0x23, 0xf3, 0x30, 0xff, 0x6e, 0xc9, 0x0c,
	0xea, 0xca, 0xc0, 0xbd, 0x81, 0xe5, 0x59, 0x1a, 0x45, 0x84, 0x0b, 0xe4, 0x40, 0x9f, 0xe7, 0xcb,
	0x4b, 0xca, 0x42, 0xdb, 0x70, 0x8c, 0xd1, 0x0a, 0xd6, 0x53, 0xe8, 0x23, 0xac, 0x06, 0x71, 0x72,
	0x1b, 0xaa, 0x1d, 0xdc, 0x6e, 0x39, 0xed, 0x51, 0x7f, 0xb2, 0xb1, 0x95, 0x17, 0xde, 0xd3, 0x30,
	0x5c, 0x65, 0xba, 0xbf, 0x0c, 0x18, 0xe8, 0x38, 0x1a, 0x83, 0xa5, 0x33, 0x34, 0xc9, 0x46, 0x1e,
	0xbd, 0x06, 0x33, 0x62, 0xf4, 0x51, 0xc4, 0x76, 0xcb, 0x31, 0x46, 0xfd, 0xc9, 0xaa, 0x12, 0x3c,
	0x94, 0x49, 0xac, 0xc0, 0x9c, 0xe6, 0xdf, 0xc7, 0xdc, 0x6e, 0xd7, 0x68, 0x59, 0x12, 0x2b, 0xd0,
	0x15, 0x60, 0xe6, 0x1b, 0x91, 0x0b, 0x5d, 0x1e, 0x53, 0x26, 0xa4, 0xf0, 0xda, 0x64, 0xa0, 0xf8,
	0xbb, 0x8c, 0xd1, 0x47, 0x9c, 0x43, 0xe8, 0x15, 0x98, 0x77, 0x24, 0x4c, 0xd2, 0x3b, 0xa9, 0x5d,
	0x27, 0x29, 0x0c, 0x39, 0xd0, 0xb9, 0xa5, 0xf3, 0x48, 0x0a, 0xd7, 0x39, 0x12, 0xc9, 0x55, 0x33,
	0x7d, 0x5d, 0x35, 0xeb, 0xde, 0x40, 0x77, 0xf9, 0x94, 0x6a, 0x93, 0xd4, 0x54, 0x6d, 0x72, 0x72,
	0xd5, 0x1d, 0xe8, 0xca, 0x10, 0x21, 0xe8, 0x84, 0xbe, 0x20, 0xaa, 0xc5, 0x72, 0x8d, 0x36, 0xa1,
	0xfb, 0xe0, 0xdf, 0xa6, 0x44, 0x9e, 0xac, 0x8d, 0xf3, 0xc0, 0xfd, 0x6d, 0xc0, 0xf2, 0x97, 0x84,
	0x0b, 0xca, 0x7e, 0xa2, 0x21, 0xf4, 0x38, 0xf1, 0x59, 0x10, 0x1f, 0xe5, 0xc3, 0xe9, 0xe0, 0x32,
	0x46, 0x2f, 0x00, 0xf2, 0xb5, 0x1c, 0x5d, 0x4b, 0xd6, 0xd5, 0x32, 0xa5, 0x62, 0x5b, 0x53, 0x7c,
	0x03, 0x26, 0x17, 0xbe, 0x48, 0xb9, 0xdd, 0x91, 0x8d, 0x5a, 0x57, 0x96, 0x3d, 0x46, 0x23, 0x46,
	0x38, 0xc7, 0x0a, 0x46, 0xff, 0x81, 0x99, 0x70, 0x4c, 0xfc, 0xd0, 0xee, 0x3a, 0xc6, 0xa8, 0x87,
	0x55, 0xe4, 0x7a, 0x80, 0xce, 0xb3, 0x1d, 0x33, 0xa9, 0x83, 0xc9, 0x8f, 0x34, 0xbb, 0x4b, 0x55,
	0x2b, 0x46, 0xc3, 0xca, 0x10, 0x7a, 0x29, 0x27, 0xec, 0x22, 0x4d, 0x0a, 0xa3, 0x65, 0xec, 0xee,
	0xc0, 0x46, 0xa5, 0x22, 0xbf, 0xa7, 0x73, 0x4e, 0x16, 0x9d, 0xdc, 0x3d, 0x29, 0xb6, 0xa8, 0xab,
	0xae, 0x5c, 0x2c, 0x6a, 0xd6, 0x22, 0x07, 0x9f, 0x60, 0xb3, 0x5a, 0x4e, 0x59, 0x18, 0xc1, 0xb2,
	0xfa, 0xf9, 0xd4, 0x4d, 0x59, 0x53, 0xdd, 0x2a, 0x88, 0x05, 0x5c, 0x9e, 0x41, 0x8d, 0x4d, 0x33,
	0x54, 0x8a, 0x1a, 0x35, 0xd1, 0xa9, 0x12, 0x2d, 0xb7, 0x28, 0xd1, 0xb7, 0xb0, 0x12, 0xcb, 0x54,
	0x42, 0x78, 0x4d, 0xb6, 0xa0, 0xfe, 0x23, 0x8c, 0x5f, 0x42, 0x57, 0xde, 0x71, 0x64, 0x42, 0xeb,
	0xc2, 0xb3, 0x96, 0x50, 0x0f, 0x3a, 0x07, 0xc7, 0xbb, 0xe7, 0x96, 0x91, 0xad, 0xa6, 0x67, 0x97,
	0xa7, 0x56, 0x6b, 0x3c, 0x86, 0x5e, 0x31, 0x5f, 0xb4, 0x0e, 0xfd, 0xa3, 0xd3, 0x2b, 0x0f, 0x9f,
	0x1d, 0xe2, 0xfd, 0xd9, 0xcc, 0x5a, 0x42, 0xab, 0xb0, 0xb2, 0x77, 0x76, 0xe2, 0x1d, 0xef, 0x9f,
	0xef, 0x4f, 0x2d, 0x63, 0xf2, 0xc7, 0x80, 0x81, 0x1a, 0x07, 0x7b, 0x48, 0x02, 0x82, 0xa6, 0xd0,
	0xd7, 0xc6, 0x83, 0x9e, 0x29, 0x2f, 0xcd, 0x4b, 0x30, 0x1c, 0x3e, 0x05, 0xa9, 0x53, 0x1d, 0x16,
	0x55, 0xd5, 0xe3, 0x53, 0xe5, 0x56, 0xc6, 0x38, 0x7c, 0xfe, 0x24, 0x56, 0x2b, 0x54, 0xfe, 0x20,
	0x3a, 0xb9, 0xda, 0xfe, 0x6a, 0xa1, 0x5a, 0x9f, 0x3f, 0x7f, 0xf8, 0xfa, 0x3e, 0x4a, 0x44, 0x9c,
	0x5e, 0x6f, 0x05, 0xf4, 0x6e, 0x5b, 0x52, 0x0e, 0x92, 0x79, 0xe8, 0x31, 0xfa, 0x8d, 0x04, 0x62,
	0x5b, 0xdc, 0x5c, 0x5d, 0xfb, 0xc1, 0xf7, 0xec, 0xd1, 0xd6, 0x1f, 0xf0, 0x88, 0x5e, 0x9b, 0x32,
	0x7e, 0xf7, 0x37, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x4b, 0xc2, 0x35, 0xd9, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TrendServiceClient is the client API for TrendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrendServiceClient interface {
	TrendSearch(ctx context.Context, in *TrendSearchRequest, opts ...grpc.CallOption) (*TrendSearchResponse, error)
	TrendSuggest(ctx context.Context, in *TrendSuggestRequest, opts ...grpc.CallOption) (*TrendSuggestResponse, error)
	TrendHistory(ctx context.Context, in *TrendHistoryRequest, opts ...grpc.CallOption) (*TrendHistoryResponse, error)
}

type trendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrendServiceClient(cc grpc.ClientConnInterface) TrendServiceClient {
	return &trendServiceClient{cc}
}

func (c *trendServiceClient) TrendSearch(ctx context.Context, in *TrendSearchRequest, opts ...grpc.CallOption) (*TrendSearchResponse, error) {
	out := new(TrendSearchResponse)
	err := c.cc.Invoke(ctx, "/trend.TrendService/TrendSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) TrendSuggest(ctx context.Context, in *TrendSuggestRequest, opts ...grpc.CallOption) (*TrendSuggestResponse, error) {
	out := new(TrendSuggestResponse)
	err := c.cc.Invoke(ctx, "/trend.TrendService/TrendSuggest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) TrendHistory(ctx context.Context, in *TrendHistoryRequest, opts ...grpc.CallOption) (*TrendHistoryResponse, error) {
	out := new(TrendHistoryResponse)
	err := c.cc.Invoke(ctx, "/trend.TrendService/TrendHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrendServiceServer is the server API for TrendService service.
type TrendServiceServer interface {
	TrendSearch(context.Context, *TrendSearchRequest) (*TrendSearchResponse, error)
	TrendSuggest(context.Context, *TrendSuggestRequest) (*TrendSuggestResponse, error)
	TrendHistory(context.Context, *TrendHistoryRequest) (*TrendHistoryResponse, error)
}

// UnimplementedTrendServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTrendServiceServer struct {
}

func (*UnimplementedTrendServiceServer) TrendSearch(ctx context.Context, req *TrendSearchRequest) (*TrendSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrendSearch not implemented")
}
func (*UnimplementedTrendServiceServer) TrendSuggest(ctx context.Context, req *TrendSuggestRequest) (*TrendSuggestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrendSuggest not implemented")
}
func (*UnimplementedTrendServiceServer) TrendHistory(ctx context.Context, req *TrendHistoryRequest) (*TrendHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrendHistory not implemented")
}

func RegisterTrendServiceServer(s *grpc.Server, srv TrendServiceServer) {
	s.RegisterService(&_TrendService_serviceDesc, srv)
}

func _TrendService_TrendSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).TrendSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trend.TrendService/TrendSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).TrendSearch(ctx, req.(*TrendSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_TrendSuggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendSuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).TrendSuggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trend.TrendService/TrendSuggest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).TrendSuggest(ctx, req.(*TrendSuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_TrendHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).TrendHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trend.TrendService/TrendHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).TrendHistory(ctx, req.(*TrendHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrendService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trend.TrendService",
	HandlerType: (*TrendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrendSearch",
			Handler:    _TrendService_TrendSearch_Handler,
		},
		{
			MethodName: "TrendSuggest",
			Handler:    _TrendService_TrendSuggest_Handler,
		},
		{
			MethodName: "TrendHistory",
			Handler:    _TrendService_TrendHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trend/trend.proto",
}
