steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/trend-find-trend:$SHORT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/trend-find-trend:latest",
        "--build-arg",
        "GITHUB_ACCESS_TOKEN=$_GITHUB_ACCESS_TOKEN",
        ".",
      ]
    dir: "trend"
  # upload image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/trend-find-trend:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/trend-find-trend:latest"]
  # upload gke
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment",
        "trend",
        "trend=gcr.io/$PROJECT_ID/trend-find-trend:$SHORT_SHA",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER"
